### ISSUE TITLE
Tracking issue for pin-project 0.4

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/pin-project#21]
Current prerelease: [0.4.0-beta.1](https://docs.rs/pin-project/0.4.0-beta.1/pin_project/)

The most important fix of this release is that pin projection has become a _safe_ operation (#18, thanks @Aaron1011)

## Changes

* `#[unsafe_project]` has been replaced with `#[pin_project]`. (#18, #33)
* The `Unpin` argument has been removed - an `Unpin` impl is now generated by default. (#18)
* Drop impls must be specified with `#[pinned_drop]` attribute instead of via a normal `Drop` impl. (#18, #33, #86)
* `Unpin` impls must be specified with an impl of `UnsafeUnpin`, instead of implementing the normal `Unpin` trait. (#18)
* ~~Changed `project` method generated by `#[pin_project]` attribute to take an `&mut Pin<&mut Self>` argument. (#47)~~ EDIT: reverted in #90
* Removed "project_attr" feature and always enable `#[project]` attribute (#94)
* `#[project]` attribute can now be used for `impl` blocks. (#46)
* `#[project]` attribute can now be used for `use` statements. (#85)
* ~~Made `#[project]` attribute disabled by default. (#36, #41)~~ EDIT: replaced with #94
* Added `project_ref` method and `#[project_ref]` attribute. (#93)
* `#[pin_project]` attribute now determines the visibility of the projection type/method is based on the original type. (#96)

## TODO

Some adjustments are needed.

* [x] Make error message more obvious (https://github.com/taiki-e/pin-project/pull/18#discussion_r308108570); done in #22
* [x] `unsafe_Unpin` vs `UnsafeUnpin` vs `unsafe_unpin` (https://github.com/taiki-e/pin-project/pull/18#discussion_r308003657); done in #40 (Adopted `UnsafeUnpin`).
* [x] Update proc-macro2, syn, and quote to 1.0; done in #23
* [ ] ~~Test code examples in README (#19)~~ EDIT: see https://github.com/taiki-e/pin-project/issues/19#issuecomment-524438264
* [x] Mention #32 in the documents; done in #34
* [x] pin-project does not interoperate well with #[cfg()] (#68)

## Unresolved issues

* [x] Different approach to `Unpin` vs `Drop` (#26); done in #86 
* [x] Change the argument type of project method back to `self: Pin<&mut Self>` (#89)

## Blockers

* [ ] ~~Whether or not `self: &mut Pin<&mut Self>` stabilizes in Rust 1.39  (https://github.com/rust-lang/rust/pull/64325)~~ EDIT: replaced with #89
* [x] Rustdoc issues (will be fixed in https://github.com/rust-lang/rust/pull/62855); see #98 
* [x] 1.0 release of proc-macro2, syn, and quote

I plan to have a few alpha releases before the blockers are resolved.

**Comment by taiki-e** [comment]
I don't list it as a blocker, but https://github.com/rust-lang/rust/issues/63281 is one of the issues to consider.

**Comment by Aaron1011** [comment]
`Mention #32 in the documents` can be checked off/removed, now that the issue is closed.

**Comment by taiki-e** [comment]
@Aaron1011 thanks 👍

**Comment by taiki-e** [comment]
Published 0.4.0-alpha.1 ([crate.io](https://crates.io/crates/pin-project/0.4.0-alpha.1), [releases](https://github.com/taiki-e/pin-project/releases/tag/v0.4.0-alpha.1))!

**Comment by taiki-e** [comment]
TR; DR: Added "Whether or not `self: &mut Pin<&mut Self>` stabilizes in Rust 1.39" (https://github.com/rust-lang/rust/pull/64325) to blocker list.

https://github.com/rust-lang/rust/pull/64325 stabilizes `self: &mut Pin<&mut Self>`.
This removes some of the hacks introduced in #47.
It can also solve some existing problems (e.g., https://github.com/tower-rs/tower/pull/326#discussion_r322422235).

However, this means will take a different approach between versions prior to 1.39 and versions 1.39 or later. This should not break compatibility, but it will cause a feature that is "supported only with rust 1.39 or later". Specifically, it is a feature that "project/project_into methods are called outside the defined scope" that is planned to be provided by #80.

Also, if stabilization is delayed, the impact on crate using async / await (e.g., tower) is too big, so merge #80 to make those features available in versions 1.39 and earlier.

**Comment by taiki-e** [comment]
I have filed #107 to fix #102. Once #107 is merged, I will release 0.4.0. As documentation fixes are no breaking changes, will be fixed in the patch versions.

**Comment by taiki-e** [comment]
Published [0.4.0](https://crates.io/crates/pin-project/). Thanks everybody for your contribution and feedback (especially @Aaron1011!).
